language: csharp
dist: xenial
mono: none
dotnet: 3.1

install:
  - dotnet restore ./elastic.log4net/elastic.log4net.linux.csproj
script:
  - dotnet build ./elastic.log4net/elastic.log4net.linux.csproj
  - dotnet restore ./elastic.log4net.Test/elastic.log4net.Test.linux.csproj
  - dotnet test ./elastic.log4net.Test/elastic.log4net.Test.linux.csproj

