language: csharp
solution: elastic.log4net.sln
install:
  - nuget restore elastic.log4net.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release elastic.log4net.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./elastic.log4net.Test/bin/Release/elastic.log4net.Test.dll

