language: csharp
dist: xenial
mono: 6.8.0
dotnet: 3.1

install:
  - dotnet restore ./elastic.log4net/elastic.log4net.csproj
script:
  - dotnet build ./elastic.log4net/elastic.log4net.csproj
  - dotnet restore ./elastic.log4net.Test/elastic.log4net.Test.csproj
  - dotnet test ./elastic.log4net.Test/elastic.log4net.Test.csproj

